imports:
    - { resource: parameters.yml }
    - { resource: security.yml }
    - { resource: services.yml }

# Put parameters here that don't need to change on each machine where the app is deployed
# http://symfony.com/doc/current/best_practices/configuration.html#application-related-configuration
parameters:
    locale: en-US
    app_locales: en-US|km-KH|zh-CN|fr-FR

framework:
    #esi:             ~
    translator:      { fallbacks: ["%locale%"] }
    secret:          "%secret%"
    router:
        resource: "%kernel.root_dir%/config/routing.yml"
        strict_requirements: ~
    form:            ~
    csrf_protection: ~
    validation:      { enable_annotations: true }
    #serializer:      { enable_annotations: true }
    templating:
        engines: ['twig']
        #assets_version: SomeVersionScheme
    default_locale:  "%locale%"
    trusted_hosts:   ~
    trusted_proxies: ~
    session:
        # handler_id set to null will use default session handler from php.ini
        handler_id:  ~
    fragments:       ~
    http_method_override: true

# Twig Configuration
twig:
    debug:            "%kernel.debug%"
    strict_variables: "%kernel.debug%"
    date:
        timezone: "%app_display_timezone%"
    globals:
        google_maps_api_key: %google_maps_api_key%

# Assetic Configuration
assetic:
    debug:          "%kernel.debug%"
    use_controller: false
    bundles:
        - AppBundle
        - WeBridgeUserBundle
        - ProjectRealtyBundle
        - CondoBundle
        - ClientBundle
        - FrontendBundle
        - CondominiumManagementBundle
        - ServiceBundle
        - PlatformBundle
    #java: /usr/bin/java
    filters:
        cssrewrite: ~
        scssphp:
            formatter: 'Leafo\ScssPhp\Formatter\Nested'
        #closure:
        #    jar: "%kernel.root_dir%/Resources/java/compiler.jar"
        #yui_css:
        #    jar: "%kernel.root_dir%/Resources/java/yuicompressor-2.4.7.jar"
    assets:
        jquery:
            inputs: '%kernel.root_dir%/../vendor/components/jquery/jquery.min.js'
            output: 'js/jquery.min.js'
        sb_admin_css:
            inputs: '%kernel.root_dir%/Resources/css/sb-admin-2.css'
            output: 'css/sb-admin-2.css'
        sb_admin_js:
            inputs: '%kernel.root_dir%/Resources/js/sb-admin-2.js'
            output: 'js/sb-admin-2.js'
        datatable_css:
            inputs: '%kernel.root_dir%/Resources/css/datatables.min.css'
            output: 'css/datatables.min.css'
        datatable_js:
            inputs: '%kernel.root_dir%/Resources/js/datatables.min.js'
            output: 'js/datatables.min.js'
        file_saver_js:
            inputs: '%kernel.root_dir%/Resources/js/FileSaver.min.js'
            output: 'js/FileSaver.min.js'
        jspdf_js:
            inputs: '%kernel.root_dir%/Resources/js/jspdf.min.js'
            output: 'js/jspdf.min.js'
        jspdf_plugin_autotable_js:
            inputs: '%kernel.root_dir%/Resources/js/jspdf.plugin.autotable.js'
            output: 'js/jspdf.plugin.autotable.js'
        html2canvas_js:
            inputs: '%kernel.root_dir%/Resources/js/html2canvas.min.js'
            output: 'js/html2canvas.min.js'
        table_export_js:
            inputs: '%kernel.root_dir%/Resources/js/tableExport.min.js'
            output: 'js/tableExport.min.js'
        jquery_ui_css:
            inputs: '%kernel.root_dir%/Resources/css/jquery-ui.css'
            output: 'css/jquery-ui.min.css'
        jquery_ui_js:
            inputs: '%kernel.root_dir%/Resources/js/jquery-ui.min.js'
            output: 'js/jquery-ui.min.js'
        jquery_cookie:
            inputs: '%kernel.root_dir%/Resources/js/jquery.cookie.js'
            output: 'js/jquery.cookie.js'
        extra_common_css:
            inputs: '%kernel.root_dir%/Resources/scss/extra-common.scss'
            output: 'css/extra-common.css'
        metis_menus_css:
            inputs: '%kernel.root_dir%/../vendor/onokumus/metismenu/dist/metisMenu.min.css'
            output: 'css/metisMenu.min.css'
        metis_menus_js:
            inputs: '%kernel.root_dir%/../vendor/onokumus/metismenu/dist/metisMenu.min.js'
            output: 'js/metisMenu.min.js'
        bootstrap_min_css:
            inputs: '%kernel.root_dir%/../vendor/twbs/bootstrap/dist/css/bootstrap.min.css'
            output: 'css/bootstrap.min.css'
        bootstrap_min_js:
            inputs: '%kernel.root_dir%/../vendor/twbs/bootstrap/dist/js/bootstrap.min.js'
            output: 'js/bootstrap.min.js'
        glyphicon_woff2:
            inputs: '%kernel.root_dir%/../vendor/twbs/bootstrap/dist/fonts/glyphicons-halflings-regular.woff2'
            output: 'fonts/glyphicons-halflings-regular.woff2'
        glyphicon_woff:
            inputs: '%kernel.root_dir%/../vendor/twbs/bootstrap/dist/fonts/glyphicons-halflings-regular.woff'
            output: 'fonts/glyphicons-halflings-regular.woff'
        font_awesome_css:
            inputs: '%kernel.root_dir%/../vendor/fortawesome/font-awesome/css/font-awesome.min.css'
            output: 'css/font-awesome.min.css'
        font_awesome_woff2:
            inputs: '%kernel.root_dir%/../vendor/fortawesome/font-awesome/fonts/fontawesome-webfont.woff2'
            output: 'fonts/fontawesome-webfont.woff2'
        font_awesome_woff:
            inputs: '%kernel.root_dir%/../vendor/fortawesome/font-awesome/fonts/fontawesome-webfont.woff'
            output: 'fonts/fontawesome-webfont.woff'
        flag_icon_css:
            inputs: '%kernel.root_dir%/../vendor/components/flag-icon-css/css/flag-icon.min.css'
            output: 'css/flag-icon.min.css'
        flag_icon_svg_cn:
            inputs: '%kernel.root_dir%/../vendor/components/flag-icon-css/flags/4x3/cn.svg'
            output: 'flags/4x3/cn.svg'
        flag_icon_svg_fr:
            inputs: '%kernel.root_dir%/../vendor/components/flag-icon-css/flags/4x3/fr.svg'
            output: 'flags/4x3/fr.svg'
        flag_icon_svg_kh:
            inputs: '%kernel.root_dir%/../vendor/components/flag-icon-css/flags/4x3/kh.svg'
            output: 'flags/4x3/kh.svg'
        flag_icon_svg_en:
            inputs: '%kernel.root_dir%/../vendor/components/flag-icon-css/flags/4x3/us.svg'
            output: 'flags/4x3/us.svg'

# Doctrine Configuration
doctrine:
    dbal:
        driver:   pdo_pgsql
        host:     "%database_host%"
        port:     "%database_port%"
        dbname:   "%database_name%"
        user:     "%database_user%"
        password: "%database_password%"
        charset:  UTF8
        # if using pdo_sqlite as your database driver:
        #   1. add the path in parameters.yml
        #     e.g. database_path: "%kernel.root_dir%/data/data.db3"
        #   2. Uncomment database_path in parameters.yml.dist
        #   3. Uncomment next line:
        #     path:     "%database_path%"

    orm:
        auto_generate_proxy_classes: "%kernel.debug%"
        naming_strategy: doctrine.orm.naming_strategy.underscore
        auto_mapping: true

# Swiftmailer Configuration
swiftmailer:
    transport:  "%mailer_transport%"
    host:       "%mailer_host%"
    username:   "%mailer_user%"
    password:   "%mailer_password%"
    spool:      { type: memory }

fos_user:
    db_driver: orm
    user_class: WeBridge\UserBundle\Entity\User
    firewall_name: main
    profile:
        form:
            type: WeBridge\UserBundle\Form\ChangePasswordFormType

ivory_ck_editor:
    default_config: condo_ck_editor
    configs:
        condo_ck_editor:
            toolbar: custom_toolbar
    toolbars:
        configs:
            custom_toolbar: [ "@tool1" , "/", "@tool2" ]
        items:
            tool1:     [ "Italic", "-", "Bold", "-", "Underline", "-", "Superscript", "-", "NumberedList", "-", "BulletedList", "-", "Outdent" , "-", "Indent", "-","JustifyLeft", "-", "JustifyCenter", "-", "JustifyRight", "-", "JustifyBlock" ]
            tool2:     [ "Table", "-", "Smiley", "-", "Format", "-", "Font", "-", "FontSize", "-", "TextColor", "-", "BGColor" ]

# PDF Configuration
knp_snappy:
    pdf:
        enabled:    true
        binary:     '%kernel.root_dir%/../vendor/h4cc/wkhtmltopdf-amd64/bin/wkhtmltopdf-amd64'
        options:    []
