# To get started with security, check out the documentation:
# http://symfony.com/doc/current/book/security.html
security:
    encoders:
        FOS\UserBundle\Model\UserInterface: bcrypt

    role_hierarchy:
        ROLE_ADMIN:
            - ROLE_ADMIN
            - ROLE_SERVICE
            - ROLE_CONDOMINIUM
            - ROLE_PROJECT
            - ROLE_USER
            - ROLE_REALTY_COMPANY
            - ROLE_DEVELOPER

    # http://symfony.com/doc/current/book/security.html#where-do-users-come-from-user-providers
    providers:
        fos_userbundle:
            id: fos_user.user_provider.username

    firewalls:
        # disables authentication for assets and the profiler, adapt it according to your needs
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        main:
            pattern: ^/
            form_login:
                provider: fos_userbundle
                csrf_token_generator: security.csrf.token_manager
                check_path: fos_user_security_check
                login_path: fos_user_security_login
                default_target_path: condo_homepage

            logout:
                path: /logout
                target: /login
            anonymous: true

    access_control:

        - { path: ^/login, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/register, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/resetting, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: '^\/([a-z]{2}-[A-Z]{2}\/){0,1}realty', role: ROLE_REALTY_COMPANY }
        - { path: '^\/([a-z]{2}-[A-Z]{2}\/){0,1}platform', role: ROLE_ADMIN }
        - { path: '^\/([a-z]{2}-[A-Z]{2}\/){0,1}service', role: ROLE_SERVICE }
        - { path: '^\/([a-z]{2}-[A-Z]{2}\/){0,1}condominium', role: ROLE_CONDOMINIUM }
        - { path: '^\/([a-z]{2}-[A-Z]{2}\/){0,1}project', role: ROLE_PROJECT }
        - { path: '^\/([a-z]{2}-[A-Z]{2}\/){0,1}developer', role: ROLE_DEVELOPER }
        - { path: '^\/([a-z]{2}-[A-Z]{2}\/){0,1}client', role: IS_AUTHENTICATED_FULLY }
        - { path: '^\/([a-z]{2}-[A-Z]{2}\/)home', role: IS_AUTHENTICATED_FULLY }
