<?php

namespace DeveloperBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * DeveloperRepository.
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class DeveloperRepository extends EntityRepository
{
}
