<?php

namespace DeveloperBundle\Repository;

use Doctrine\ORM\EntityRepository;
use DeveloperBundle\Entity\Developer;
use ProjectRealtyBundle\Constant\PaymentStatus;
use RealtyCompanyBundle\Entity\RealtyCompany;

/**
 * ProjectPaymentRepository.
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class DeveloperPaymentRepository extends EntityRepository
{
    /**
     * @param Developer $developer
     *
     * @return QueryBuilder
     */
    public function findAllByDeveloper(Developer $developer)
    {
        return $this->createQueryBuilder('payment')
            ->join('payment.developer', 'developer')
            ->join('payment.realtyCompany', 'realtyCompany')
            ->where('developer = :developer')
            ->andWhere('payment.status != :draft')
            ->setParameter('developer', $developer)
            ->setParameter('draft', PaymentStatus::DRAFT)
            ->addOrderBy('payment.creationDate', 'DESC')
            ->addOrderBy('payment.status', 'ASC');
    }

    /**
     * @param RealtyCompany $company
     *
     * @return QueryBuilder
     */
    public function findAllByRealtyCompany(RealtyCompany $company)
    {
        return $this->createQueryBuilder('payment')
            ->join('payment.realtyCompany', 'realtyCompany')
            ->where('realtyCompany = :realtyCompany')
            ->setParameter('realtyCompany', $company)
            ->addOrderBy('payment.creationDate', 'DESC')
            ->addOrderBy('payment.status', 'ASC');
    }
}
