<?php

namespace CondoBundle\Repository;

use Doctrine\ORM\EntityRepository;
use CondoBundle\Entity\Condominium;
use Doctrine\DBAL\Query\QueryBuilder;

/**
 * CompanySupplierRepository.
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CompanySupplierRepository extends EntityRepository
{
    /**
     * Gets all company supplier for given a condominium.
     *
     * @param Condominium $condominium
     *
     * @return QueryBuilder
     */
    public function findAllCompanySuppliersForCondo(Condominium $condominium)
    {
        return $this->createQueryBuilder('companySupplier')
            ->where('companySupplier.condominium = :condominium')
            ->setParameter('condominium', $condominium);
    }

    /**
     * Gets all individual suppliers for given name and condominium.
     *
     * @param Condominium $condominium
     * @param $name
     *
     * @return QueryBuilder
     */
    public function findAllCompanySuppliersForNameAndCondo(
        Condominium $condominium,
        $name
    ) {
        $result = $this
            ->createQueryBuilder('companySupplier')
            ->where('companySupplier.condominium = :condominium')
            ->setParameter('condominium', $condominium);
        if ($name !== '') {
            $result
                ->andWhere('companySupplier.name LIKE :name')
                ->setParameter('name', $name.'%');
        }

        return $result;
    }
}
