<?php

namespace CondoBundle\Repository;

use Doctrine\ORM\EntityRepository;
use CondoBundle\Entity\Unit;
use Datetime;

/**
 * CondominiumNewsRepository.
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CondominiumNewsRepository extends EntityRepository
{
    /**
     * Gets all news for a given unit.
     *
     * @param Unit $unit
     *
     * @return QueryBuilder
     */
    public function findAllForUnit(Unit $unit)
    {
        return $this->createQueryBuilder('condoNews')
            ->where('condoNews.condominium = :condo')
            ->andwhere('condoNews.isPublished = true')
            ->andWhere('condoNews.publishDate <= :now')
            ->andWhere('condoNews.endDate >= :now OR condoNews.endDate is NULL')
            ->setParameter('now', new Datetime())
            ->setParameter('condo', $unit->getCondominium()->getId())
            ->orderBy('condoNews.publishDate', 'DESC');
    }
}
