<?php

namespace CondoBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * CurrencyRepsitory.
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CurrencyRepository extends EntityRepository
{
    /**
     * Gets all currencies.
     *
     * @return QueryBuilder
     */
    public function findAllCurrencies()
    {
        $result = $this->createQueryBuilder('currency');

        return $result;
    }
}
