<?php

namespace CondoBundle\Repository;

use Doctrine\ORM\EntityRepository;
use WeBridge\UserBundle\Entity\User;

/**
 * DeveloperRepository.
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class DeveloperRepository extends EntityRepository
{
    /**
     * Gets all Developer for a given manager.
     *
     * @param User $user
     *
     * @return \Doctrine\ORM\QueryBuilder
     */
    public function findDevelopersByManager(User $user)
    {
        return $this->createQueryBuilder('developer')
            ->join('developer.managers', 'managers')
            ->where('managers = :manager')
            ->setParameter('manager', $user)
            ->orderBy('developer.name');
    }
}
