<?php

namespace CondoBundle\Repository;

use Doctrine\ORM\EntityRepository;
use CondoBundle\Entity\Condominium;

/**
 * ExpendCategoryRepository.
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ExpendCategoryRepository extends EntityRepository
{
    /**
     * Get all Expend Categoryby condominium.
     *
     * @param Condominium $condominium
     *
     * @return QueryBuilder
     */
    public function findAllExpendByCondominium(Condominium $condominium)
    {
        return $this->createQueryBuilder('expendCategory')
            ->where('expendCategory.condominium = :condominium')
            ->setParameter('condominium', $condominium);
    }
}
