<?php

namespace CondoBundle\Repository;

use Doctrine\ORM\EntityRepository;
use CondoBundle\Entity\Condominium;

/**
 * IncomeCategoryRepository.
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class IncomeCategoryRepository extends EntityRepository
{
    /**
     * Gets all income category for a given.
     *
     * @param Condominium $condominium
     *
     * @return QueryBuilder
     */
    public function findAllIncomeCategoryByCondominium(Condominium $condominium)
    {
        return $this->createQueryBuilder('incomeCategory')
            ->where('incomeCategory.condominium = :condominium')
            ->setParameter('condominium', $condominium);
    }
}
