<?php

namespace CondoBundle\Repository;

use Doctrine\ORM\EntityRepository;
use CondoBundle\Entity\Condominium;
use CondoBundle\Constant\InvoiceStatus;
use DateTime;

/**
 * IncomeRepository.
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class InvoiceRepository extends EntityRepository
{
    /**
     * Gets invoices for a given condominium, type and date.
     *
     * @param Condominium $condominium
     * @param string      $type
     * @param DateTime    $from
     * @param DateTime    $to
     *
     * @return QueryBuilder
     */
    public function findInvoicesByCondominiumAndDate(
        Condominium $condominium,
        $type,
        DateTime $from,
        DateTime $to
    ) {
        $result = $this->createQueryBuilder('invoice')
            ->where('invoice.condominium = :condominium');
        if ($type === 'creation') {
            $result
                ->andWhere('invoice.creationDate >= :from')
                ->andWhere('invoice.creationDate <= :to');
        }
        if ($type === 'paid') {
            $result
                ->andWhere('invoice.status = :status')
                ->andWhere('invoice.paymentDate >= :from')
                ->andWhere('invoice.paymentDate <= :to')
                ->setParameter('status', InvoiceStatus::PAID);
        }
        $result
            ->setParameter('condominium', $condominium)
            ->setParameter('from', $from)
            ->setParameter('to', $to)
            ->orderBy('invoice.creationDate', 'ASC');

        return $result;
    }
}
