<?php

namespace CondoBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * IssueCommentRepository.
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class IssueCommentRepository extends EntityRepository
{
}
