<?php

namespace CondoBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * LandlordRepository.
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class LandlordRepository extends EntityRepository
{
}
