<?php

namespace CondoBundle\Repository;

use CondoBundle\Entity\Resident;
use Doctrine\ORM\EntityRepository;
use WeBridge\UserBundle\Entity\User;

/**
 * ResidentRepository.
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ResidentRepository extends EntityRepository
{
    public function getClientMenuData(User $user)
    {
        /** @var Resident[] $residents */
        $residents = $this->createQueryBuilder('resident')
            ->addSelect('unit')
            ->addSelect('condo')
            ->join('resident.unit', 'unit')
            ->join('unit.condominium', 'condo')
            ->where('resident.user = :user')
            ->setParameter('user', $user)
            ->addOrderBy('condo.name', 'ASC')
            ->addOrderBy('unit.roomNumber', 'ASC')
            ->getQuery()
            ->getResult();

        $result = [
            'condominiums' => [

            ],
        ];

        foreach ($residents as $resident) {
            $unit = $resident->getUnit();
            $condo = $unit->getCondominium();

            if (!isset($result['condominiums'][$condo->getId()])) {
                $result['condominiums'][$condo->getId()] = [
                    'id' => $condo->getId(),
                    'name' => $condo->getName(),
                    'units' => [],
                ];
            }

            $result['condominiums'][$condo->getId()]['units'][] = [
                'id' => $unit->getId(),
                'roomNumber' => $unit->getRoomNumber(),
            ];
        }

        return $result;
    }
}
