<?php

namespace CondoBundle\Repository;

use CondoBundle\Entity\Service;
use Doctrine\ORM\EntityRepository;

/**
 * ServiceUnavailabilityRepository.
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ServiceUnavailabilityRepository extends EntityRepository
{
    /**
     * Gets all unavailabilities that are not yet expired for a given service.
     *
     * @param Service $service
     *
     * @return \Doctrine\ORM\QueryBuilder
     */
    public function findAllNotOutdatedForService(Service $service)
    {
        $qb = $this->createQueryBuilder('unavailability')
            ->where('unavailability.service = :service')
            ->andWhere('unavailability.endDateTime > :now')
            ->orderBy('unavailability.startDateTime', 'ASC')
            ->orderBy('unavailability.endDateTime', 'ASC')
            ->setParameter('service', $service)
            ->setParameter('now', new \DateTime())
        ;

        return $qb;
    }
}
