<?php

namespace CondoBundle\Repository;

use CondoBundle\Entity\Condominium;
use Doctrine\ORM\EntityRepository;
use WeBridge\UserBundle\Entity\User;

/**
 * ServiceRepository.
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ServiceRepository extends EntityRepository
{
    /**
     * Gets all service for a manager.
     * e.g. Used to get the service list to display on the left menu for a service
     * manager.
     *
     * @param User $user
     *
     * @return \Doctrine\ORM\QueryBuilder
     */
    public function findServicesForManager(User $user)
    {
        $qb = $this->createQueryBuilder('service')
            ->join('service.managers', 'managers')
            ->where('managers = :manager')
            ->setParameter('manager', $user)
            ->orderBy('service.title', 'ASC');

        return $qb;
    }

    /**
     * Gets all services available for a given condominium.
     *
     * @param Condominium $condo
     *
     * @return \Doctrine\ORM\QueryBuilder
     */
    public function findAvailableServicesForCondominium(Condominium $condo)
    {
        $qb = $this->createQueryBuilder('service')
            ->join('service.condominiums', 'condo')
            ->where('condo = :condo')
            ->setParameter('condo', $condo);

        return $qb;
    }
}
