<?php

namespace CondoBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * ServiceAvailabilityRepository.
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ServiceAvailabilityRepository extends EntityRepository
{
}
