<?php

namespace CondoBundle\Repository;

use Doctrine\ORM\EntityRepository;
use CondoBundle\Entity\Condominium;

/**
 * UnitTypeRepository.
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UnitTypeRepository extends EntityRepository
{
    /**
     * Gets all unit type for a given condominium.
     *
     * @param Condominium $condo
     *
     * @return \Doctrine\ORM\QueryBuilder
     */
    public function findAllUnitTypesForCondominium(Condominium $condo)
    {
        $qb = $this->createQueryBuilder('unitType')
            ->join('unitType.condominium', 'condo')
            ->where('condo = :condo')
            ->setParameter('condo', $condo);

        return $qb;
    }
}
