<?php

namespace ProjectRealtyBundle\Repository;

use Doctrine\ORM\EntityRepository;
use ProjectRealtyBundle\Entity\CondoProjectListingProfile;

/**
 * CondoProjectListingProfile.
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CondoProjectListingProfileRepository extends EntityRepository
{
    /**
     * Gets all condominium public list for a given frontend.
     *
     * @return \Doctrine\ORM\QueryBuilder
     */
    public function findProjectPublicListing($type)
    {
        $query = $this->createQueryBuilder('cp');
        $query->join('cp.project', 'project');
        $query->where('cp.published = :published');
        if ($type !== null) {
            $query->andWhere('cp.type = :type');
            $query->setParameter('type', $type);
        }
        $query->setParameter('published', true);
        $query->orderBy('project.creationDate', 'DESC');

        return $query;
    }
}
