<?php

namespace ProjectRealtyBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * ProjectBookingRepository.
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ProjectBookingRepository extends EntityRepository
{
}
