<?php

namespace ProjectRealtyBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * ProjectUnitStatusRepository.
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ProjectUnitStatusRepository extends EntityRepository
{
}
