<?php

namespace ProjectRealtyBundle\Repository;

use Doctrine\ORM\EntityRepository;
use Doctrine\ORM\QueryBuilder;
use ProjectRealtyBundle\Entity\CondominiumProject;

/**
 * ProjectPaymentRepository.
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ProjectPaymentRepository extends EntityRepository
{
    /**
     * @param CondominiumProject $project
     *
     * @return QueryBuilder
     */
    public function findAllByProject(CondominiumProject $project)
    {
        return $this->createQueryBuilder('payment')
            ->join('payment.unit', 'unit')
            ->where('unit.project = :project')
            ->setParameter('project', $project)
            ->orderBy('payment.creationDate', 'DESC')
        ;
    }
}
