<?php

namespace GenericOrderingServiceBundle\Repository;

use CondoBundle\Entity\Service;
use Doctrine\ORM\EntityRepository;
use GenericOrderingServiceBundle\Entity\ShoppingCart;
use WeBridge\UserBundle\Entity\User;

/**
 * ShoppingCartRepository.
 *
 * This class was generated by the PhpStorm "Php Annotations" Plugin. Add your own custom
 * repository methods below.
 */
class ShoppingCartRepository extends EntityRepository
{
    public function findUserShoppingCart(
        User $user,
        Service $service
    ) {
        /** @var ShoppingCart[] $result */
        $result = $this->createQueryBuilder('cart')
            ->andWhere('cart.user = :user')
            ->andWhere('cart.service = :service')
            ->andWhere('cart.isLocked = false')
            ->setParameter('service', $service)
            ->setParameter('user', $user)
            ->setMaxResults(1)
            ->getQuery()
            ->getResult()
        ;

        if (empty($result)) {
            return;
        }

        return $result[0];
    }
}
