<?php

namespace GenericOrderingServiceBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * ShoppingCartItemRepository.
 *
 * This class was generated by the PhpStorm "Php Annotations" Plugin. Add your own custom
 * repository methods below.
 */
class ShoppingCartItemRepository extends EntityRepository
{
}
