<?php

namespace RealtyCompanyBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * CompanyContactRepository.
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CompanyContactRepository extends EntityRepository
{
}
