<?php

namespace RealtyCompanyBundle\Repository;

use Doctrine\ORM\EntityRepository;
use Doctrine\ORM\QueryBuilder;
use WeBridge\UserBundle\Entity\User;

/**
 * RealtyCompanyRepository.
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class RealtyCompanyRepository extends EntityRepository
{
    /**
     * gets all Realty Company.
     *
     * @return QueryBuilder
     */
    public function findAllRealtyCompany()
    {
        $queryBuilder = $this->createQueryBuilder('realtyCompany');
        $queryBuilder->orderBy('realtyCompany.id', 'DESC');

        return $queryBuilder;
    }

    /**
     * gets all Realty Company by Manager.
     *
     * @param User $user
     *
     * @return QueryBuilder
     */
    public function findAllRealtyCompanyByManager($user)
    {
        $queryBuilder = $this->createQueryBuilder('realtyCompany')
            ->join('realtyCompany.managers', 'managers')
            ->where('managers = :manager')
            ->setParameter('manager', $user)
            ->orderBy('realtyCompany.name', 'ASC')
            ->getQuery()
            ->getResult();

        return $queryBuilder;
    }
}
